name: wordpress-varnish
type: service
from: varnish
fromVersionConstraint: "^1.0.0"
fromVersion: "1.0.1"
title: Varnish (WordPress)


labels:
- wordpress
- varnish

configs:
- name: wordpress
  title: Drupal preset
  filepath: /etc/gotpl/preset/wordpress.vcl.tmpl
  config: wordpress.vcl.tmpl

env:
- name: VARNISH_CONFIG_PRESET
  value: wordpress
